### DISCUSSION TITLE
GitHub Actions Build

### DISCUSSION THREAD

**Discussion by callumeveratt** [nanoframework/Home#1373] [Q&A] [answered]
Hey all,

Trying to get a nanoframework project to build with GitHub actions but seem to be hitting an error - I'm a bit lost at where to look next to would appreciate any help. Not sure if I'm missing something / doing something wrong.

My actions file runs the following:

````
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Add NF
      uses: nanoframework/nanobuild@v1

    - name: Restore NuGet packages
      run: nuget restore .

    - name: Build
      run: msbuild . /verbosity:normal /p:Configuration=Release /nologo
````

This runs and seems to build until it runs the nanoFramework MetadataProcessor:

> MetaDataProcessor:
  Starting nanoFramework MetadataProcessor...
 C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\NFProjectSystem.MDP.targets(779,5): error MSB4062: The "GenerateBinaryOutputTask" task could not be loaded from the assembly C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll. Could not load file or assembly 'file:///C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\nanoFramework\v1.0\nanoFramework.Tools.BuildTasks.dll' or one of its dependencies. An attempt was made to load a program with an incorrect format. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. 

At this point the build fails. I've found some previous issues around the MetadataProcessor but these seem to have been closed and fixed some time ago. So I'm hoping I'm just doing something wrong and someone could advise.

**Comment by callumeveratt** [comment, marked as answer]
Self solved. After reading through some threads back to 2022 in the Discord I managed to get it working:

````
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: nanoframework/nanobuild@v1

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    
    - name: Install NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /verbosity:normal /p:Configuration=Release /nologo
````
